language: ruby
bundler_args: --path vendor/bundle
script: bundle exec rake
sudo: false
branches:
  only: [262-as-259]
env:
  - RUBYOPT=-w
before_install:
  - gem install bundler
  - bundle config --local without local_development
gemfile:
  - gemfiles/mime_types_1.16.gemfile
  - gemfiles/mime_types_2.0.gemfile
  - gemfiles/mime_types_2.1.gemfile
  - gemfiles/mime_types_2.2.gemfile
  - gemfiles/mime_types_2.3.gemfile
  - gemfiles/mime_types_2.latest.gemfile
  - gemfiles/mime_types_edge.gemfile
rvm:
  - 2.1.7
  - 2.2.3
matrix:
  fast_finish: true
